{% set name = "icalendar" %}
{% set version = "6.3.1" %}
{% set sha256 = "a697ce7b678072941e519f2745704fc29d78ef92a2dc53d9108ba6a04aeba466" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  host:
    - pip
    - python
    - hatchling >=1.27.0
    - hatch-vcs

  run:
    - python
    - python-dateutil
    - backports.zoneinfo  # [py<39]
    - python-tzdata

test:
  source_files:
    - src/icalendar/tests
  imports:
    - icalendar
  commands:
    - pip check
    - pytest -xvs -k "not (test_timezone_names_are_known)" --ignore=src/icalendar/tests/test_with_doctest.py
  requires:
    - pip
    - pytest
    - hypothesis
    - pytz

about:
  home: https://github.com/collective/icalendar
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: iCalendar parser/generator
  description: |
    The icalendar package is a parser/generator of iCalendar files for use with
    Python.
  doc_url: https://icalendar.readthedocs.io
  dev_url: https://github.com/collective/icalendar

extra:
  recipe-maintainers:
    - stuertz
