travis:
  secure:
    BINSTAR_TOKEN: RVtgmqYJsNJggM77pDg4BJRtHuEPlbjd1SQfd+SeITzzY4+MlAIEvAtrergj5xV/XCkNZysQNn7ACxH8MwwqVb9pGaLDSZB5Zq8iOW45h9SfNxP//keSUz245XQTPPlI+a8AahsY8NLYIYNvW77P5xJ+zqoaWWPNaz+hAH0KUdhD+jNTdfPETgxlsrKiBfCHqWHTFF7SJUSet+D8h80dtX5+ZBE0i1VILB+U/P1Xw2fJpY/GuK+wvn+KxwC6UvQp3Bw5f0Y1prxTgok/3yYQce/47zBlOFqDJhNWbcMZH/6j9EAO7xgVOElxre7ainIRk0/gjNZscy1jjkXWC5zVDwH8ZnA2OjiM+SYKgrI/uofVTYk5C/cN07odLC9VnXsyOPjSM8NqoisWGVhAPm6UKDqkiFqBFotD6SfiLDn1B/oD2SYfGydBlPwilledJ7FdyDaf6j8I0o++UsR/DzJO258Lj+MIWTlqB8s8jEuHegC4mPxk+SdVa6xJ5Cio8+5IZx1wVQn/Hd26A7hNC8HoAAy3jdFsAFVvgQ1aXOEHGkKrQK14szGlg32t5hfXG8ZBFAtocu1jqxdb37+6cN+WEl0MEBkDrJ6BEtp4kte9DMeu+lFG9rchdzXFxrvB3nb3b53OWLEQt/D2uqJkQ6p3XxVSauTjYpAlC7Verok0lVE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
