travis:
  secure:
    BINSTAR_TOKEN: qUYzTr0RFKlXivGjQY6A1UzM/FYe8iIs+dIl+okRd2tWthooDl3S6Cl6wifSJLWak/lMAt/Qt/dCDC1AdfRlvYrqeUfLT9NUKMzkrpWWPxWPRMbClRVZ1R2rVpHtIjXtTH/hvGr9McC8rudswNRDna/kAFpzrUOWTPSqoXGZ7F5S9LupX4H+U3+Ugf0lD8o/lvQW7ECHl+q+D0iUDEfhnpP27oh/vZO2g1KBF0ePRewR0pIaTVXH5qTV1e4IRG79CMwl5d8z5YxjYwHgNDYqy09HackVQB36Fm/w8LU3Mg2MlgVEG8iXA2cBv/7ZZH+VFITI6RZ9cUBDKXREHZ6hdkbvpOa7mkNw09O4dEtASjl3ogz+EVpQrRWLdaTtJyUJZ1yAU63mYvXUs22p4paM9zxuslKf7qR0e8KxYbFWzN/4fIP+hHDwDvo2MmIJZoy673ROj/EDPncnaVmWxsLjUxrE19ag+VR1CPCmDXP6R+bOx7l5HAfvMSn33PesWsrUZmINTu8DI4HYGMX46P8HTgcEW5TyBXreGSn6O0Ohg6XVCQ7GRrrcrd8aD3L4or3M7VSRIpqw1AXu7YZVfu2VoI+BeZVug+tQt/LcVf1kdDao3c5ViI8c2F0aCBkMTUl6MeX6kxuVpPOUhmmHaekdChQ89dLUn1uBvcT02H97NXg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
